version: '3'
services:
  weather-tracker:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${MYSQL_URL}
    depends_on:
      - cguru-mysql
    volumes:
      - ./src:/app/src
  cguru-mysql:
    container_name: cguru-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cguru_weather
      MYSQL_USER: cguru
      MYSQL_PASSWORD: cguru
    ports:
      - 3306:3306
